
//redux actions
export const ACTION_TYPE = {
    NEW_GAME:'NEW_GAME',
    SET_LEVEL: 'SET_LEVEL',
    SELECT_CELL: 'SELECT_CELL',
    SHOW_CELL: 'SHOW_CELL',
    SET_MINES: 'SET_MINES',
    SHOW_MINES: 'SHOW_MINES'
};
